name: Validate Entries

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  check-internal-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Run consistency checks
        run: python scripts/check_entries.py
